export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";
export const SET_SELECTED_INGREDIENT = "SET_SELECTED_INGREDIENT";
export const TOGGLE_SELECTED_INGREDIENT_MODAL = "TOGGLE_SELECTED_INGREDIENT_MODAL";
